[package]
name = "emir"
version = "0.5.0"
edition = "2024"
description = "Just my try at graphic library. If you want to use it - you better have a real damn reason to"
license = "GPL-3.0-or-later"

[dependencies]
minifb = "0.28.0"
bytemuck = { version = "1", features = ["derive"] }
fontdue = "0.9.4"
thiserror = "2.0.20"
image = "0.25.10"
log = "0.4.34"
