[package]
name = "emir"
version = "0.1.0"
edition = "2024"
description = "Just my try at graphic library. If you want to use it - you better have a real damn reason to"
license = "GPL-3"
exclude = [
    "src/main.rs",
    "font.ttf"
]

[dependencies]
minifb = "0.28.0"
bytemuck = { version = "1", features = ["derive"] }
fontdue = "0.9.4"
